import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeCard from '../components/homecard'
import MainCard from '../components/MainCard'
import HeaderCard from '../components/headercard'
import PaginationRounded from '../components/pagination'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.headerCardContainer}>
          <HeaderCard
            image="/yoor_header.png"
          />
        </div>
        <MainCard>
          <div>
            <HomeCard
              title="なりたい自分になるための癒しの場。momoさんインタビュー🎤"
              date="2022年09月20日"
              image="https://yoor-blog.up.seesaa.net/image/E9AD94E6B395E4BDBFE38184momoE381AEE59BBDE794BBE5838F.jpeg"
              des="こんにちは、ベルです。 お買い物などのお釣りで新500円玉をもらうと何となくツイてる気がします。 なんとなく運気がたまる気がするので、新500円玉貯金でも始めてみようかと思います。 さて、yoorでは様々な分野で専門知識を持ったオーナー様が活躍しています。 幅広い分野の方にスポットライトを当てていきたいと考えて"
              link="https://blog.yoor.jp/article/491475163.html"
            />
            <HomeCard
              title="なりたい自分になるための癒しの場。momoさんインタビュー🎤"
              date="2022年09月20日"
              image="https://yoor-blog.up.seesaa.net/image/E9AD94E6B395E4BDBFE38184momoE381AEE59BBDE794BBE5838F.jpeg"
              des="こんにちは、ベルです。 お買い物などのお釣りで新500円玉をもらうと何となくツイてる気がします。 なんとなく運気がたまる気がするので、新500円玉貯金でも始めてみようかと思います。 さて、yoorでは様々な分野で専門知識を持ったオーナー様が活躍しています。 幅広い分野の方にスポットライトを当てていきたいと考えて"
              link="https://blog.yoor.jp/article/491475163.html"
            />
            <HomeCard
              title="なりたい自分になるための癒しの場。momoさんインタビュー🎤"
              date="2022年09月20日"
              image="https://yoor-blog.up.seesaa.net/image/E9AD94E6B395E4BDBFE38184momoE381AEE59BBDE794BBE5838F.jpeg"
              des="こんにちは、ベルです。 お買い物などのお釣りで新500円玉をもらうと何となくツイてる気がします。 なんとなく運気がたまる気がするので、新500円玉貯金でも始めてみようかと思います。 さて、yoorでは様々な分野で専門知識を持ったオーナー様が活躍しています。 幅広い分野の方にスポットライトを当てていきたいと考えて"
              link="https://blog.yoor.jp/article/491475163.html"
            />
          </div>
          <div className={styles.image}>
            <Image src="/search.png" alt="Search Logo" width={300} height={60} />
          </div>
        </MainCard>
        <div className={styles.bottomPage}>
          <PaginationRounded />
        </div>
      </main >
      <footer className={styles.footer}>
        <a
          href="https://blog.seesaa.jp/">
          <span className={styles.title}>
            SEESAA BLOG
          </span>
        </a>
      </footer>
    </div >
  )
}
